modLoader = "kotlinforforge" #mandatory
loaderVersion = "[4,)"
license = "${mod_license}"

[[mods]]
    modId = "${mod_id}"
    version = "${mod_version}"
    displayName = "${mod_name}"
    authors = "${mod_authors}"
    description = '''${mod_description}'''

[[dependencies."${mod_id}"]]
    modId = "forge"
    mandatory = true
    versionRange = "${forge_version_range}"
    ordering = "NONE"
    side = "BOTH"

[[dependencies."${mod_id}"]]
    modId = "minecraft"
    mandatory = true
    versionRange = "${minecraft_version_range}"
    ordering = "NONE"
    side = "BOTH"

[[dependencies."${mod_id}"]]
    modId="itemphysiclite"
    mandatory=false
    versionRange="[1.6.6,)"
    ordering="NONE"
    side="BOTH"

[[dependencies."${mod_id}"]]
    modId="itemphysic"
    mandatory=false
    versionRange="[1.8.9,)"
    ordering="NONE"
    side="BOTH"

[[dependencies."${mod_id}"]]
    modId="superbwarfare"
    mandatory=false
    versionRange="[0.8.8,)"
    ordering="NONE"
    side="BOTH"

[[dependencies."${mod_id}"]]
    modId="tacz"
    mandatory=false
    versionRange="[1.1.6,)"
    ordering="NONE"
    side="BOTH"

[[dependencies."${mod_id}"]]
    modId="pointblank"
    mandatory=false
    versionRange="[1.9.6,)"
    ordering="NONE"
    side="BOTH"

[[mixins]]
    config="itemphysicguns.mixins.json"
